version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Maven Build
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Générer le rapport Jacoco
          command: mvn jacoco:report
      - run:
          name: Télécharger le rapport sur Codecov
          command: curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}
      - run:
          name: Run Checkstyle
          command: |
            mvn checkstyle:checkstyle
            if [ $? -eq 0 ]; then
              echo "Checkstyle passed"
              echo "Checkstyle Status: Passed" > checkstyle_status.txt
            else
              echo "Checkstyle failed"
              echo "Checkstyle Status: Failed" > checkstyle_status.txt
            fi
      - run:
          name: Ajouter le badge Checkstyle
          command: |
            if grep -q "Passed" checkstyle_status.txt; then
              curl -s https://img.shields.io/badge/Checkstyle-Passed-brightgreen > checkstyle_badge.svg
            else
              curl -s https://img.shields.io/badge/Checkstyle-Failed-red > checkstyle_badge.svg
            fi
            # Déplacer le badge dans le répertoire spécifié
            mv checkstyle_badge.svg /home/nas-wks01/users/uapv2307467/Donnees_itinerantes/public_html/checkstyle_badge.svg

  upload-to-codecov:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - build
