version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Maven Build
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Générer le rapport Jacoco
          command: mvn jacoco:report
      - run:
          name: Télécharger le rapport sur Codecov
          command: curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}
      - run:
          name: Run Checkstyle
          command: |
            mvn checkstyle:checkstyle
            if [ $? -eq 0 ]; then
            curl -s https://img.shields.io/badge/Checkstyle-Passed-brightgreen > badge.svg
            else
            curl -s https://img.shields.io/badge/Checkstyle-Failed-red > badge.svg
            fi
            - run:
                command: |
                  mv badge.svg ./badge.svg
                  sed -i 's|!\\[Checkstyle Status\\](.*)|![Checkstyle Status](badge.svg)|' README.md
            - store_artifacts:
                path: badge.svg
                destination: badge.svg

  upload-to-codecov:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - build
