version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Maven Build
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Générer le rapport Jacoco
          command: mvn jacoco:report
      - run:
          name: Télécharger le rapport sur Codecov
          command: curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle
      - run:
          name: Check Checkstyle result and update badge
          command: |
            # Vérifier si Checkstyle a échoué
            if grep -q "Checkstyle: There are" target/checkstyle-result.xml; then
              # Si Checkstyle échoue (erreurs détectées), générer un badge rouge
              curl -s "https://img.shields.io/badge/Checkstyle-failed-red" > checkstyle-badge.svg
            else
              # Si Checkstyle passe (pas d'erreurs), générer un badge vert
              curl -s "https://img.shields.io/badge/Checkstyle-passed-brightgreen" > checkstyle-badge.svg
            fi
            gh release create v1.0 checkstyle-badge.svg --title "Checkstyle Badge" --notes "Badge status for Checkstyle"

  upload-to-codecov:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - build
