version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Maven Build
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Générer le rapport coco
          command: mvn jacoco:report
      - run:
          name: Télécharger le rapport sur coco
          command: curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle

  upload-to-codecov:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - build
