version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Maven Build
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                
orbs:
  codecov: codecov/codecov@4.0.1
workflows:
  upload-to-codecov:
    jobs:
      - checkout 
      - codecov/upload




